### PR TITLE
replace around with hooks

### PR DESCRIPTION
**Pull request by grosser**

### CODE REVIEW

**Comment by grosser** [comment]
@splattael what do you think of putting this into minitest-around so an alternative is out there as gem ?

**Comment by Nakilon** [comment]
So it's not implemented?
Wanted to use maxitest in a long integration test and discovered it seems to be incompatible with -hooks:

```ruby
require "minitest/autorun"
require "minitest/hooks"

describe "" do
  before :all do
    p :all
  end
  it "1" do p 1 end
  it "2" do p 2 end
end
```
```none
:all
1
.:all
2
.
```

**Comment by grosser** [comment]
do you need to use minitest/hooks ?

**Comment by grosser** [comment]
ah same without :/

**Comment by grosser** [comment]
ah yeah that never worked ... I think the argument is just ignored, would be nice to raise argumenterror
... `let_all` can help ... just call it in `before` to get the same behavior

**Comment by grosser** [comment]
and a PR to make `before/after` raise or even support `:each` + `:all` would be nice ... could reuse let_all under the hood ...

**Comment by Nakilon** [comment]
```ruby
  let_all :_ do
    p :all
  end
  before :all do
    _
  end
```
works! Thank you for a quick response.

**Comment by Nakilon** [comment]
This hack is weird though in the way that if there was an exception in let_all it gets reevaluated for every example.

**Comment by grosser** [comment]
maybe don't call it `_` to avoid 👁️ ♋

**Comment by grosser** [comment]
yeah, but caching exceptions is also super weird :)

**Comment by Nakilon** [comment]
Some workaround:
```ruby
describe "" do
  let_all :failing do
    p :all
    fail
    true
  rescue
    false
  end
  before do
    fail unless failing
  end
  it "1" do p 1 end
  it "2" do p 2 end
end
```

**Comment by Nakilon** [comment]
Or even
```ruby
  let_all :before_all do
    p :all
    fail "all"
    false
  rescue
    $!
  end
  before{ before_all and fail before_all }
```
to reraise the caught error.

**Comment by grosser** [comment]
https://github.com/grosser/maxitest/pull/53 to block these broken cases and add `before :all` looks good ?

**Comment by grosser** [comment]
afaik this is not doable atm without making the ordering un-intuitive
created new issue for continued discussion https://github.com/grosser/maxitest/issues/54

**Pull request closed without merging**
